### static file server
GET http://localhost:8080/tower/fixtures/b64.txt

### tower-http-server
GET http://localhost:8080/tower/fixtures/ed25519.sk

###
GET http://localhost:8080/tower/fixtures/b64.txt
Range: bytes=0-100


### tower-http directory
GET http://localhost:8080/tower/fixtures/

###
GET http://localhost:8080/fixtures/
